### ISSUE TITLE
Distillation Tower won't form

### ISSUE THREAD

**Issue by ZAKsPop** [TwistedGate/ImmersivePetroleum#105]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.2.2-154

### Immersive Petroleum Version

4.0.0-14

### Current Behaviour

I'm running in Create mode. I've built the derrick, Pump Jack and oil tank. All formed without any issue. I built this Distillation tower and it will not form.

### Expected Behaviour

I expect to right click the redstone engineering block and it forms.

### Reproduction Steps

1. I build it
2. I right click the redstone engineering block with the hammer
3. Nothing happens
4. so on and so on....
5. 

### Debug Crash Log

It doesn't crash

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Not reproducable, did you use the right slabs? That tends to be the usual mistake.

**Comment by ZAKsPop** [comment]
Thanks.
