### ISSUE TITLE
Cannot connect between client and server when inserted into existing game, netty.io.exception thrown.

### ISSUE THREAD

**Issue by Pantheris2019** [TwistedGate/ImmersivePetroleum#106]
### Minecraft Version

1.18.2

### Immersive Engineering Version

40.1.80

### Immersive Petroleum Version

4.0.0-14

### Current Behaviour

When connecting to the server (after inserting the mod into an existing game because our players are tired of continual worldwipes.) we get a netty.io.exception thrown and the text is as follows: cannot connect to server because blusunrize.immersiveengineering.api.crafting.FluidTagInput.write(net.minecraft.network.FriendlyByteBuf)" because "recipe.inputFluidSecondary" is null.

### Expected Behaviour

Being able to connect to the server after inserting the mod into an existing world should have no effect on being able to connect to the server.

### Reproduction Steps

1. Install Immersive Petroleum to an existing server save.
2.  Attempt to connect.
3. REQUIREMENT: this must be a modpack you are suddenly updating to include Immersive petrol.

### Debug Crash Log

No Crash, none generated.

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by voidsong-dragonfly** [comment]
We need an actual log, please, not just your copy-paste.

**Comment by Dweebington** [comment]
I am experiencing the same error verbiage at successful login to my server. I have added the newest release of IP to an existing world.

Attached is my server debug log from the time of the event as there was no crash; simply a denial of access with a netty.io.exception. My client makes no mention in the debug but I can provide that as well.

[logs_debug.log](https://github.com/TwistedGate/ImmersivePetroleum/files/10145438/logs_debug.log)

**Comment by Golden-Hall** [comment]
Also experiencing the same issue, commenting to add info:
Have tried generating a new world for my test server and still throws the same exception

**Comment by TwistedGate** [comment]
If it still persists once i make another release with this fix then please re-open this.
