### ISSUE TITLE
Adding mod after world gen breaks reservoirs

### ISSUE THREAD

**Issue by Brutalcreeper** [TwistedGate/ImmersivePetroleum#107]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.2.2-154

### Immersive Petroleum Version

ImmersivePetroleum-1.18.2-4.0.0-14

### Current Behaviour

Running a seismic survey after world generation causes reservoirs to not be identified
using the same world seed i was able to get a confirmed reservoir at the same location on my server where it was just empty

### Expected Behaviour

Reservoirs should still be identifiable after world gen

### Reproduction Steps

1. create world without the mod
2. add IP
3. run seismic survey on a reservoir
4. once found its unable to identify the reservoir

### Debug Crash Log

https://pastebin.com/63yH7ptt

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Ofcourse no reservoirs would be in chunks that were generated before IP was added, move to a new area on an existing pre-IP world and the reservoirs should start to apear again.

**Comment by voidsong-dragonfly** [comment]
The IE mineral deposits _also_ do not work this way anymore, FYI: Because of their dependence upon worldgen, neither IP reservoirs nor IE minerals have retrogen. Think of them generating like biome-specific features, as a part of worldgen itself.

**Comment by Brutalcreeper** [comment]
My apologies, i thought that was still a thing
