### ISSUE TITLE
[1.8.2] Motor boat minor issues

### ISSUE THREAD

**Issue by Zahkriiven** [TwistedGate/ImmersivePetroleum#109]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.2.2-154

### Immersive Petroleum Version

4.0.0-14

### Current Behaviour

- The player is sitting on air
![image](https://user-images.githubusercontent.com/25531677/205176431-a4ab8376-f60d-4c37-ab87-c0ec0dfab50c.png)
- Tooltip about the upgrades are not displayed after breaking it and picking it back up.
![image](https://user-images.githubusercontent.com/25531677/205177035-ef0a7ad7-5bd8-4687-8d96-42b191620692.png)
- The paddling using the paddle upgrade is faster than vanilla (not really an issue but feels off)
- No sound when paddling

### Expected Behaviour

- Player should be sitting on the boat
- Tooltips should display after breaking the motor boat
- I expected the motor boat with paddles be similar to vanilla boats

### Reproduction Steps

1. Get a motor boat
2. Sit on it. See player model
3. Add paddles upgrade and move. See that paddles are faster and silent compared to vanilla
4. Break the motor boat and pick it up. No upgrades are shown in the item's tooltip.

### Debug Crash Log

https://pastebin.com/cLNJUSJY

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Fixed all :)
