### ISSUE TITLE
Crush client\server then generating new chunk in the end

### ISSUE THREAD

**Issue by SAIANBY** [TwistedGate/ImmersivePetroleum#111]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.2.2-154

### Immersive Petroleum Version

4.0.0-14

### How did it happen?

Crush server then generating new chunk in the end.

### Crash Log

https://gist.github.com/SAIANBY/242ebb4316ab7518b56baedc73b95a7c

**Comment by TwistedGate** [comment]
Already been fixed #108
