### ISSUE TITLE
Cannot Connect to Server when running with PneumaticCraft (1.18)

### ISSUE THREAD

**Issue by Paulie820** [TwistedGate/ImmersivePetroleum#115]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.2.2-154

### Immersive Petroleum Version

1.18.2-4.0.0-15

### Current Behaviour

Cannot connect to server, error message appears as follows:

*Player* lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "blusunrize.immersiveengineering.api.crafting.FluidTagInput.write(net.minecraft.network.FriendlyByteBuf)" because "recipe.inputFluidSecondary" is null

This occurs while running Immersive Petroleum 1.18.2-4.0.0-15 and any 1.18 PneumaticCraft version together. This only occurs on servers, single player worlds load without issue.

### Expected Behaviour

Successful connection to server.

### Reproduction Steps

1. Load Immersive Petroleum 1.18.2-4.0.0-15 and PneumaticCraft on the same instance
2. Join server with same mods

### Debug Crash Log

No crash occurs

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Duplicate #106
