### ISSUE TITLE
Sulfur Recovery Unit - Output doesn't work correctly

### ISSUE THREAD

**Issue by MrTubzy456** [TwistedGate/ImmersivePetroleum#117]
### Minecraft Version

1.16.5

### Immersive Engineering Version

5.1.0-48

### Immersive Petroleum Version

3.4.0-13

### Current Behaviour

Visually all slots for fluids are blue. There is no output slot by color. 

### Expected Behaviour

Output should be orange. Even after testing all slots I couldn't get the diesel pulled out of the machine.

### Reproduction Steps

I read the manual and it says the output is on the left, so I tested it. This is after I connected sulfuric diesel pipes and water pipes to the machine, I know I connected those properly because it filled up. I did test pulling out of all three slots and none of them seem to want to work for me.

### Debug Crash Log

n/a

### Information for the reader.

Visually all slots for fluids are blue. There is no output slot by color. Output should be orange. Even after testing all slots I couldn't get the diesel pulled out of the machine. I read the manual and it says the output is on the left, so I tested it. This is after I connected sulfuric diesel pipes and water pipes to the machine, I know I connected those properly because it filled up. I did test pulling out of all three slots and none of them seem to want to work for me.

**Comment by TwistedGate** [comment]
> Visually all slots for fluids are blue. There is no output slot by color.

Now thats just plain wrong.

![grafik](https://user-images.githubusercontent.com/31029668/206924247-2a3df2b4-11bc-4428-b3f0-169bf9370cdc.png)

Whats this then?
![grafik](https://user-images.githubusercontent.com/31029668/206924294-f7c3a432-bf86-4053-b662-b60e3de0b86e.png)

Blue always signifies input
Orange always signifies output

Regardless wether or not its for items or fluids, but in this case it's all about fluids.

All of this is described in the manual

**Comment by TwistedGate** [comment]
as for
> I did test pulling out of all three slots

Two of which are inputs and were not designed to be pulled from.

As for the output, nothing needs to be pulled from there. The machine automaticly outputs the finished result if there is a tank connected to it which has space for it.

**Comment by MrTubzy456** [comment]
> as for
> 
> > I did test pulling out of all three slots
> 
> Two of which are inputs and were not designed to be pulled from.
> 
> As for the output, nothing needs to be pulled from there. The machine automaticly outputs the finished result if there is a tank connected to it which has space for it.

I was making sure I had the right ones hooked up when I tested that, but something broke my base and we had to remove the region files. When I formed a new sulfur recover unit, it formed correctly with the correct colors for the inputs and outputs. I don't know if it formed incorrectly and caused the problems on the server that made us have to remove the region files or not.

What I posted was what I saw. I was trying top give you tons of info so that you can better understand what's happening. I wish I had taken a screenshot because now it seems to be fixed. The output was blue before we removed that part of my base.
