### ISSUE TITLE
Compat Issue with diagonal fences mod

### ISSUE THREAD

**Issue by MCJEModder2026** [TwistedGate/ImmersivePetroleum#118]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.2.2-154

### Immersive Petroleum Version

4.0.0-16

### Current Behaviour

diagonal fences mod makes it impossible to form the derrick multiblock
[Screenshot](https://media.essential.gg/5425770f-1dd1-4409-6742-fafcd3d0cd00)

### Expected Behaviour

the multiblock forms and ignores that the fences are diagonal

### Reproduction Steps

build derrick
try to form it

### Debug Crash Log

[ByteBin](https://bytebin.lucko.me/R4RsxqUjHD) or [Crashy](https://crashy.net/JECHPVYKhufKdLrn5p4L)

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by MCJEModder2026** [comment]
the debug stick can be used to fix the issue but that is not survival friendly

**Comment by TheKidThatCodes** [comment]
and #101 is still not fixed

**Comment by TwistedGate** [comment]
Wrong ID.

**Comment by emanuele246gi** [comment]
I also have this issue

**Comment by MrMorgan0** [comment]
Hi @TheKidThatCodes , i find how we can **FIX** that... i don't know why [Fuzs](https://legacy.curseforge.com/members/Fuzs/projects) didn't add **config** file to [DiagonalFences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences) mod, but we can fix it in another way. He add the **Tag** for fences that shouldn't be diagonal, so we should fix that by adding several code lines in that file. If you have installed [OpenLoader ](https://www.curseforge.com/minecraft/mc-mods/open-loader)mod, you also can fix it easily. Follow steps below and it will be fixed.

**GAME SHOULD BE CLOSED**

1. Go to your Minecraft directory **mods** folder,
2. Find there **DiagonalFences-v3.1.0-1.18.2** and open it with **WinRAR** archiver,
3. Open folder **data**>**diagonalfences**>**tags**>**blocks** and there you can find `.json` file named `non_diagonal_fences.json`,
4. Open it and replace this code. Make sure that u have selected all code, jsut press `Ctrl + A` and `Ctrl + V` after copy code below:
```
{
  "replace": false,
  "values": [
    {
      "id": "assorteddecor:colorizer_fence",
      "required": false
    },
	
	{
      "id": "immersiveengineering:alu_fence",
      "required": false
    },
	
	{
      "id": "immersiveengineering:steel_fence",
      "required": false
    }
	
  ]
}
``` 
**DON'T FORGET TO SAVE THAT FILE**
Here's result of that
![2023-04-29_19 30 01](https://user-images.githubusercontent.com/105439991/235310741-9027d023-27a6-45f3-9674-d2dd978950ce.png)

I hope you did all things right and it help you to fix that issue..
**P.S. Close the issue if you haven't any questions ;)**
**P.S.S If u want to fix it with OpenLoader also write here, I'll help you as well**

**Comment by MCJEModder2026** [comment]
whats winrar?

**Comment by MCJEModder2026** [comment]
> Hi @TheKidThatCodes , i find how we can **FIX** that... i don't know why [Fuzs](https://legacy.curseforge.com/members/Fuzs/projects) didn't add **config** file to [DiagonalFences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences) mod, but we can fix it in another way. He add the **Tag** for fences that shouldn't be diagonal, so we should fix that by adding several code lines in that file. If you have installed [OpenLoader ](https://www.curseforge.com/minecraft/mc-mods/open-loader)mod, you also can fix it easily. Follow steps below and it will be fixed.
> 
> **GAME SHOULD BE CLOSED**
> 
> 1. Go to your Minecraft directory **mods** folder,
> 2. Find there **DiagonalFences-v3.1.0-1.18.2** and open it with **WinRAR** archiver,
> 3. Open folder **data**>**diagonalfences**>**tags**>**blocks** and there you can find `.json` file named `non_diagonal_fences.json`,
> 4. Open it and replace this code. Make sure that u have selected all code, jsut press `Ctrl + A` and `Ctrl + V` after copy code below:
> 
> ```
> {
>   "replace": false,
>   "values": [
>     {
>       "id": "assorteddecor:colorizer_fence",
>       "required": false
>     },
> 	
> 	{
>       "id": "immersiveengineering:alu_fence",
>       "required": false
>     },
> 	
> 	{
>       "id": "immersiveengineering:steel_fence",
>       "required": false
>     }
> 	
>   ]
> }
> ```
> 
> **DON'T FORGET TO SAVE THAT FILE** Here's result of that ![2023-04-29_19 30 01](https://user-images.githubusercontent.com/105439991/235310741-9027d023-27a6-45f3-9674-d2dd978950ce.png)
> 
> I hope you did all things right and it help you to fix that issue.. **P.S. Close the issue if you haven't any questions ;)** **P.S.S If u want to fix it with OpenLoader also write here, I'll help you as well**

this issue is meant for a permanent fix not some hacky patch

**Comment by MrMorgan0** [comment]
Winrar just like 7Zip

**Comment by MCJEModder2026** [comment]
is there a macos alternative

**Comment by MrMorgan0** [comment]
> 

Winrar is just for MacOs too, you can downlaod it [here](https://www.win-rar.com/rar-linux-mac.html?&L=0)

**Comment by MCJEModder2026** [comment]
as i said before, this issue is for a permanent fix, not a hacky patch

**Comment by MrMorgan0** [comment]
> as i said before, this issue is for a permanent fix, not a hacky patch

It is what it is...

There is two ways in my opinion how to permanent fix it, and you also need to write that on Diagonal Fences issue page.

@TwistedGate Should add `non_diagonal_fences` tag into the Steel Fence in he's code or  Fuzs should add Config file for Diagonal Fences mod, where you can configurate which kind of fences will not able to be diagonal.

**Comment by TwistedGate** [comment]
> Should add non_diagonal_fences tag into the Steel Fence

Steel fences are from Immersive Engineering and not from IP.


And closing because Stale.
