### ISSUE TITLE
Crude oil fluid has tag that prevents it being stacked in tanks from other mods

### ISSUE THREAD

**Issue by MCJEModder2026** [TwistedGate/ImmersivePetroleum#119]
### Minecraft Version

1.18.2

### Immersive Engineering Version

same as #118

### Immersive Petroleum Version

same as #118

### Current Behaviour

the crude oil fluid has the "pressurized" tag and prevents it from being merged with crude oil without the tag
[Screenshot](https://media.essential.gg/6c932464-c000-4ec2-5d87-3a8e5cbe8a00)

### Expected Behaviour

the fluid does not have issues with merging with itself

### Reproduction Steps

make derrick (i had to use debug stick to fix fences bc im using same pack as #118)
extract the crude oil using pipes and tanks from other mods ( mekanism , integrated dynamics, tanks from mob grind utils)
it wont stack

### Debug Crash Log

same as #118 except i added collosal chests

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Fixed by 3182a60aee7365e02ad0dd747865f9ef5a4d25c2

And for the record: i don't want to see `same as #118` ever again.

**Comment by MrMorgan0** [comment]
I found how to fix fences, see https://github.com/TwistedGate/ImmersivePetroleum/issues/118 post!
