### ISSUE TITLE
[Question] How to use the seismic survey tool? 1.18.2

### ISSUE THREAD

**Issue by ClickerFrich** [TwistedGate/ImmersivePetroleum#120]
Versions:
ImmersiveEngineering-1.18.2-8.3.0-155
ImmersivePetroleum-1.18.2-4.0.0-16

### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

I can't figure out how to use the seismic survey tool. I accidentally found oil with derrick once. In this addon should generate some kind of oil beacons at the bedrock? I have Biomes o' plenty installed, maybe nothing is displayed because of it?

**Comment by TwistedGate** [comment]
Suggestion template is for *suggestions* not questions.
![RTFM](https://cdn.discordapp.com/emojis/499559424864681994.webp)
