### ISSUE TITLE
Core drill can't find oil deposits

### ISSUE THREAD

**Issue by Markyps** [TwistedGate/ImmersivePetroleum#121]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.2.2-154

### Immersive Petroleum Version

4.0.0-16

### Current Behaviour

I spent about 3 hours hoping to find an oil field. Maybe I do not know how the mod works on the new version. Because I didn't find any fashion guides for the new version. I created a lot of worlds so I didn 't find it in the end

### Expected Behaviour

The assembly is based on the extraction of oil from the mod. At the same time, more than one deposit has not been found

### Reproduction Steps

1.Creating a new world
2.I take out a core drill with an energy source from the creative
3.And I don't find more than one oil field

### Debug Crash Log

https://gist.github.com/Markyps/2f2a915fa3aa3efdd290ab4c46b3a718

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by ClickerFrich** [comment]
Yea, core drill doesn't find oil. For 1.18.2 I find seismic survey tool, but there are no guides for this in the book.. I find oil once accidenty by derrick, but I spend 2 hours for this.

P.S. 
I found the guide in the book now, if you turn the game into English language
So use English translation by default..

**Comment by Markyps** [comment]
And how to use seismic survey tool

**Comment by ClickerFrich** [comment]
> And how to use seismic survey tool

![123](https://user-images.githubusercontent.com/74198574/209474393-5d347657-d79e-4914-8608-e2d30ed4af36.png)

**Comment by ClickerFrich** [comment]
> And how to use seismic survey tool

Take a buckshot cartridge in your hand, then right-click to seismic survey for load cartridge. Then right-click one more time. Then right-click after shot.

**Comment by Markyps** [comment]
Due to the fact that there was an old translation in the manual, I used a drill. Thank you for your help

**Comment by Markyps** [comment]
We would quickly translate the book into all languages so that there would be no such misconceptions

**Comment by Markyps** [comment]
Now you can close this issue
