### ISSUE TITLE
The flare installation does not burn liquids

### ISSUE THREAD

**Issue by Markyps** [TwistedGate/ImmersivePetroleum#122]
### Minecraft Version

1.16.5

### Immersive Engineering Version

8.2.2-154

### Immersive Petroleum Version

4.0.0-16

### Current Behaviour

The flare unit does not burn liquids, 250mB of liquid enters it and nothing happens. The manual says that it burns at a rate of 100mB per tick

### Expected Behaviour

I expected that the liquid would disappear. I would not like to install third-party mods for liquid disposal

### Reproduction Steps

1.I'm setting up a flare installation
2.Liquid is fed through the pipes of the Immersive Engineering mod
3.The liquid is not burned

### Debug Crash Log

https://gist.github.com/Markyps/bdc549ae8b66b5601ef39cab89af87c3

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
![RTFM](https://cdn.discordapp.com/emojis/499559424864681994.webp)
![grafik](https://user-images.githubusercontent.com/31029668/209588509-66be08d5-e650-458e-8069-976d4e20f3bf.png)
https://github.com/TwistedGate/ImmersivePetroleum/blob/1.16.5/src/main/resources/assets/immersivepetroleum/manual/en_us/flarestack.txt#L4-L6

Either apply a redstone signal, or invert it with a screwdriver to be on at full power by default

**Comment by Markyps** [comment]
I found everything what the problem was when I tried to change the burning rate, I accidentally broke the code of the flare installation. So you can close this topic
