### ISSUE TITLE
No oil fields

### ISSUE THREAD

**Issue by Homyatos** [TwistedGate/ImmersivePetroleum#127]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.3.0-155

### Immersive Petroleum Version

4.0.0-16

### Current Behaviour

The core sample drill does not display deposits of liquids, and the pumpjack cannot extract anything.
![image](https://user-images.githubusercontent.com/121966737/210614035-6401caa2-6372-4d0c-8e46-64ba39227355.png)

### Expected Behaviour

I thought that everything would work as in the early versions, it was possible to extract oil.

### Reproduction Steps

1. I used the core sample drill

### Debug Crash Log

https://pastebin.com/cJcuttzF

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
![RTFM](https://cdn.discordapp.com/emojis/499559424864681994.webp)
