### ISSUE TITLE
Spreadsheet needs to be set to anyone with the link can access

### ISSUE THREAD

**Issue by dudebehinddude** [TwistedGate/ImmersivePetroleum#128]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

The spreadsheet for `ImmersivePetroleum 3.4.0-13+` under [this](https://github.com/TwistedGate/ImmersivePetroleum/wiki/%5B1.16.5%5D-IP-3.3.0:-Modpack-Developers#config) page in the wiki says `access denied` when opening it.

**Comment by TwistedGate** [comment]
Should be fixed now.
