### ISSUE TITLE
[1.16.5] Config generates .bak copy every time the game starts up.

### ISSUE THREAD

**Issue by whitebear60** [TwistedGate/ImmersivePetroleum#13]
Flaxbeard#233 still happens on Forge 36.1.4, IP 1.16.5-3.2.0-3, IE 1.16.5-4.2.4-134.

**Comment by ZephyrWindSpirit** [comment]
Essentially any forge update right now, this an issue. The game hangs when saving or moving dimensions and ultimately I'm forced to kill my client each time.
