### ISSUE TITLE
[1.18.2] Survey results broken updating from build 16 to 17

### ISSUE THREAD

**Issue by Zahkriiven** [TwistedGate/ImmersivePetroleum#130]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.3.0-155

### Immersive Petroleum Version

4.0.0-17

### How did it happen?

1. Play with 4.0.0-16 and generate a survey result with no reservoir.
2. Update to 4.0.0-17.
3. Hold the generated survey result.

Additionally, survey results with a reservoir were transformed to "Air" reservoirs that contains 0 buckets.
![image](https://user-images.githubusercontent.com/25531677/212777810-d4e2aee6-5887-4c0a-a038-5cdf30685bef.png)

Player data (Zipped because .dat is not supported by GH):
[inventory.zip](https://github.com/TwistedGate/ImmersivePetroleum/files/10429884/inventory.zip)

### Crash Log

https://pastebin.com/4yTPi0Ey

**Comment by TwistedGate** [comment]
Just a headsup.

This also makes surveys from 17 incompatible and will result in them crashing the game instead, **but this is a nessesary evil.**

(Read the commit description for a little more detail)
