### ISSUE TITLE
Pumpjack crash after completion with hammer

### ISSUE THREAD

**Issue by MatejHorn** [TwistedGate/ImmersivePetroleum#135]
### Minecraft Version

1.16.5

### Immersive Engineering Version

0.12-98

### Immersive Petroleum Version

1.1.9

### How did it happen?

Multiplayer server, Sevtech ages, 1.12.2. Crash on completion of pumpjack with hammer. Subsequent crashes when loading world. I dont expect you to fix error, just reporting, for others not to be as lost as I was few minutes ago, I can see that you are no longer supporting that version of Minecraft ....

[crash-2023-02-17_21.50.12-client.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/10771717/crash-2023-02-17_21.50.12-client.txt)

### Crash Log

https://github.com/TwistedGate/ImmersivePetroleum/files/10771717/crash-2023-02-17_21.50.12-client.txt

**Comment by TwistedGate** [comment]
Using MC-1.16.5 to report a 1.12.2 crash which also has it's support closed nearly 2 years ago?
