### ISSUE TITLE
[1.18.2] Distillation Tower recipe works differently than described on the Wiki

### ISSUE THREAD

**Issue by TrkvonStpd1e11** [TwistedGate/ImmersivePetroleum#137]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### Immersive Petroleum Version

1.18.2-4.0.0-17

### Current Behaviour

In current recipe, energy consumed per tick is (energy / time) * 2. Like in oil recipe, default value of time is 1 and default value of energy is 1024, so the energy consumed when processing oil is 2048IF/tick, and every processing cost only 1 tick. But if you set value of time to 2, the energy consumed would be 1024IF/tick, and every processing cost 2 ticks. In addition, if the value of energy is bigger than 16000, the recipe won't work.

### Expected Behaviour

Like the description in Wiki:
**time**: The amount of time in ticks it takes until the input has been processed.
**energy**: The minimum power **per tick** required.
That means energy consumed per tick **only** depends on "energy".

### Reproduction Steps

1. Copy the data folder in IP jar file, create a datapack.
2. Open oil.json in data\immersivepetroleum\recipes\distillationtower.
3. Change "time" value from 1 to any number bigger than 1 and smaller than 1024, save the change.
4. Load the datapack in the game, check energy consumption rate of Distillation Tower when processing oil.

### Debug Crash Log

https://pastebin.com/qkW1t1Jj

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TrkvonStpd1e11** [comment]
As far as I know, the 1.16.5 version of IP works perfectly on this recipe. Is this because the 1.18.2 is a branch of Flaxbeard:1.16.3, so there are some unsolved issues?

**Comment by voidsong-dragonfly** [comment]
I think you are very confused about how the tower is supposed to work in 1.18.2. All of the default recipes consume 1024IF per recipe and run one tick long, for 1024IF/t. The energy value in the datapack is the total energy for the entire recipe, the time of 1 for one single tick. The recipes are working as inteded. You'll note that the docs for 1.18.2 on the wiki tab haven't been written yet. Where are you getting 2048IF/t from?

**Comment by TrkvonStpd1e11** [comment]
> I think you are very confused about how the tower is supposed to work in 1.18.2. All of the default recipes consume 1024IF per recipe and run one tick long, for 1024IF/t. The energy value in the datapack is the total energy for the entire recipe, the time of 1 for one single tick. The recipes are working as inteded. You'll note that the docs for 1.18.2 on the wiki tab haven't been written yet. Where are you getting 2048IF/t from?

From testing in game, using energy meter and modified energy pipes.

**Comment by TrkvonStpd1e11** [comment]
The problem is, actually, you can't process recipe with energy value bigger than 16000. Like if I want a recipe take 50 ticks to process, consuming 1024IF/tick, then the energy value would be 51200, and the recipe won't work.

**Comment by voidsong-dragonfly** [comment]
> From testing in game, using energy meter and modified energy pipes.

I quite literally did testing to make sure this was not an issue in my own game, and it consumed 1024IF/t. Do you have the config set to a 2x power multiplier or something?    
    
    
> The problem is, actually, you can't process recipe with energy value bigger than 16000. Like if I want a recipe take 50 ticks to process, consuming 1024IF/tick, then the energy value would be 51200, and the recipe won't work.

I... okay? The tower isn't designed for that, and the recipe style has been confirmed as not changing. You're just going to be plum out of luck for that, recipes are expected to stay within the bounds of the tower's current limits.
