### ISSUE TITLE
[1.16.5] Diesel or gasoline can't be used as fuel to Drill or Buzzsaw.

### ISSUE THREAD

**Issue by MaterexPL** [TwistedGate/ImmersivePetroleum#14]
When I'm trying to fill Buzzsaw or Mining Drill from Immersive Engineering which Diesel nothing happens.

**Comment by TwistedGate** [comment]
Fixed for next release (bb7220534a7aa840c30f49e67d2938b80ff593d5)

**Comment by MaterexPL** [comment]
Nice ^^
