### ISSUE TITLE
Reservoirs not generating in certain biomes/dimensions

### ISSUE THREAD

**Issue by araheos** [TwistedGate/ImmersivePetroleum#144]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Immersive Petroleum Version

4.1.0-19

### Current Behaviour

All reservoirs are only being generated in "minecraft:overworld". In any other dimensions or in "minecraft:the_void" biomes no reservoirs are being generated no matter how the config is set. This affects modded dimensions (reference is ftb stoneblock 3) and vanilla dimensions like the nether.  
On top of that the command "ip reservoir locate" returns "No reservoir found" if and only if the player is in a place where no reservoirs can generate. If reservoirs CAN generate and none are found it will instead return "Something bad happened"

### Expected Behaviour

Reservoirs should generate in all whitelisted dimensions and biomes but not in blacklisted ones. With the default settings this would mean that in a default minecraft world reservoirs should generate everywhere but the end dimension. 
On top of that the command "ip reservoir locate" should never return "Something bad happened".

### Reproduction Steps

1. Install a clean save with IE and IP with specified versions.
2. Create two worlds
   a) normal minecraft world
   b) flat world with type void
3. Fly/walk around using "ip reservoir locate"
4. Go to the nether and do the same
5. Change setting for dimension and biome filtering
6. Repeat Step 2-4

### Debug Crash Log

https://pastebin.com/5aJw1NSA

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Reservoirs do not spawn if ores dont spawn either.

That goes for flatworlds aswell

**Comment by araheos** [comment]
Alright that makes much more sense. Although I would highly recommend changing this in future updates, since this behaviour makes this mod practically unusable for skyblock or similar modpacks

**Comment by TwistedGate** [comment]
Even if the reservoirs would spawn, the derrick still requires to be above 63 *and* bedrock for it to function properly. And im not gonna change that any time soon~
