### ISSUE TITLE
CTD when holding survey item and alt/windows-tabbing

### ISSUE THREAD

**Issue by MaxWasUnavailable** [TwistedGate/ImmersivePetroleum#145]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Immersive Petroleum Version

4.1.0-19

### How did it happen?

A user was testing a modpack I was creating, and reported they had a crash to desktop when holding a survey item and alt or windows-tabbing.

Log:
[hs_err_pid11716.log](https://github.com/TwistedGate/ImmersivePetroleum/files/11133779/hs_err_pid11716.log)

### Crash Log

https://github.com/TwistedGate/ImmersivePetroleum/files/11133779/hs_err_pid11716.log

**Comment by TwistedGate** [comment]
Tried the same thing in a clean instance with *just* IE and IP?

Also VM Crashes are rather impossible to debug..

**Comment by MrMorgan0** [comment]
Just don't use this combination when holding **survey item**, or delete mods named [Windowed Borderless](https://www.curseforge.com/minecraft/mc-mods/fullscreen-windowed-borderless-for-minecraft) and [Fps Reducer](https://www.curseforge.com/minecraft/mc-mods/fps-reducer) of course if they installed. I think those mods could cause issues like this.
