### ISSUE TITLE
[Suggestion] Update mod to 1.19.3

### ISSUE THREAD

**Issue by CamBobTheGreatYT** [TwistedGate/ImmersivePetroleum#146]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

Me and my friends wanted to use this mod on our 1.19.3 immersive engineering server but were disappointed to find that it was not available for that game version

**Comment by TwistedGate** [comment]
Cool, but that aint what this template is for.

https://gist.github.com/TwistedGate/3bb4837f450dbc1b1557876422151b63#when-comes-the-next-release
