### ISSUE TITLE
I found imcompatibility between ImmediatelyFast Reforged and Immersive Petroleum

### ISSUE THREAD

**Issue by chemlzh** [TwistedGate/ImmersivePetroleum#154]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### Immersive Petroleum Version

1.18.2-4.1.0-21

### Current Behaviour

I have installed a modpack called TskimiCanopyCraft:Terra Evolution (https://www.mcmod.cn/modpack/560.html), and modified it by installed Immersive Petroleum. Entering the game didn't cause any problem, so I placed the seismic survey tool, loaded buck shots into the machine, and started it. Then the machine freezed a few moments, and then crash.
At first I doubt if there's imcompatibility between map mod and Immersive Petroleum. However, after debugging for a while, I realized it was ImmediatelyFast Reforged that made the game crashed, since this mod may modify the behavior of entities and block entities.

### Expected Behaviour

Start the seismic survey tool, it ought to give me a scroll (map?) indicating the oil reservoir.

### Reproduction Steps

1. Installed forge and TSCC:TE modpack (which has ImmediatelyFast Reforge mod).
2. Enter the game and create a TFC world.
3. Place the seismic survey tool.
4. Fill the machine with buck shots.
5. Start it.

### Debug Crash Log

https://gist.github.com/chemlzh/d1bb985cad3531e93bb3e55d8770685d

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by Plaer1** [comment]
It's safe generally to just remove immedeatlyfast, that mod (on my PC) actually causes BIG stutter when I open menus. at least on my machine it's very mid.
