### ISSUE TITLE
[Suggestion] Update to newer versions? And upgraded machines

### ISSUE THREAD

**Issue by MommaDragon** [TwistedGate/ImmersivePetroleum#158]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

This is moreso a request to update this mod to be compatible with newer versions of Minecraft (including 1.19.2) than an actual "suggestion" thing, mostly because Petroleum is such a good addon.

That, and maybe upgrading from standard-issue Excavators and Pumpjacks. We have access to the Deep Dark, so maybe some Echo shards could help extract material faster? Not sure if the idea will be accepted, but it's still worth a shot to suggest improved machinery.

**Comment by TwistedGate** [comment]
https://github.com/TwistedGate/ImmersivePetroleum/wiki/Frequently-Asked-Questions#general-faq
