### ISSUE TITLE
[1.16.5/1.18.2] Recipe warning with kubejs

### ISSUE THREAD

**Issue by MundM2007** [TwistedGate/ImmersivePetroleum#159]
### Minecraft Version

1.16.5 / 1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.16.5-5.1.0-148.jar / ImmersiveEngineering-1.18.2-8.4.0-161.jar 

### Immersive Petroleum Version

 ImmersivePetroleum-1.16.5-3.4.0-20.jar / ImmersivePetroleum-1.18.2-4.1.0-21.jar

### Current Behaviour

The recipe issue with kubejs described in #31 also appears in 1.18.2. The Recipes still get added and you can add new recipes it just calls this warning I've posted an comment saying the reason for this: 

> @TwistedGate The reason for this error java.lang.IllegalArgumentException: Unexpected json object seems to be that kubejs doesn't correctly detect the chance in the output item for destillation and hydrotreating, which create this error if the chance is not given. This also applies to adding recipes, which confused me at first, cause this value shouldn't be required. My suggestion would be that you make the chance value optional and default to 1.0.

Also I have a question (which is also in the original comment.): Another question: Why does every fluid input and Coker's output require a tag?

### Expected Behaviour

That recipes dont give warnings in kubejs

### Reproduction Steps

1. install kubejs and immersive petroleum
2. Start the game
3. See error in kubejs Server Log

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by MundM2007** [comment]
the debug log if needed
[debug.log](https://github.com/TwistedGate/ImmersivePetroleum/files/12232799/debug.log)

**Comment by TwistedGate** [comment]
Should be taken care of by 69f7ddf97f1797bf49e99e3503e32d6a8c9760b8
