### ISSUE TITLE
[1.16.5 suggestion] Gasoline can be used in flarestack

### ISSUE THREAD

**Issue by SteelBlue8** [TwistedGate/ImmersivePetroleum#16]
The ability to use gasoline in a flarestack in the newer version in order to get rid of it- right now, I'm just constantly breaking and rebuilding the multiblock structures of my gasoline storage tanks because there simply aren't any methods of using it that are practical to be automated at a large scale. Alternatively: More large scale usages for gasoline, perhaps a multiblock method of turning into power like a stirling engine, or a method of using it for smelting, like a rotary kiln. Napalm and portable generators are cool, but not useful for dealing with the huge quantities of gasoline that you end up with running a distillation tower for any significant period of time.

**Comment by TwistedGate** [comment]
Will be a thing next release 00ee3a8e34c8882f767610c20cba1ad973adbdf7
