### ISSUE TITLE
Napalm-related Crash

### ISSUE THREAD

**Issue by BalefulHarbinger** [TwistedGate/ImmersivePetroleum#170]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.3-167

### Immersive Petroleum Version

ImmersivePetroleum-1.19.2-4.2.0-23

### How did it happen?

I apologize if this isn't very helpful, as I'm unable to find a totally consistent way to reproduce this crash. I only have IE and IP loaded, and I was taking buckets of napalm and dumping them everywhere in creative (to quickly burn down a forest), but occasionally when doing so the game would crash during unclear circumstances. I've tried several times to more accurately identify what exactly causes the crash to occur. The most I'm able  to do is string together a ton of napalm over trees, and when the puddles first start to ignite, *bam*, crash. This crash also bricks the world and makes it crash whenever I try re-entering it.

### Crash Log

https://gist.github.com/BalefulHarbinger/efa0794a7a1f573b683d8b169c5f28f6

**Comment by BalefulHarbinger** [comment]
Unfortunately, the latest release hasn't solved the issue. Using the same scenario as before I cause Minecraft to crash just as before. The world-bricking occurs much the same as well. https://gist.github.com/BalefulHarbinger/2138815bbf7c1170db00d3695343bdad

And this is the crashlog it gives when I try to enter an affected world, if that helps identify the issue:
https://gist.github.com/BalefulHarbinger/b3e4ddf43c473c11642cba112e3bb688

**Comment by TwistedGate** [comment]
I can not for the life of me get it to do the same thing.

Been trying to force it with `/fill ~-48 ~ ~-48 ~47 ~ ~47 immersivepetroleum:napalm_fluid_block` for the past hour and it just refuses to happen, neither before or after the "hopefull fix"

**Comment by BalefulHarbinger** [comment]
I can't figure out why its not happening on your end either :/

I did the same command you did, and while it didn't happen as quick as with my "chain together napalm buckets over trees", it still crashed it:
https://gist.github.com/BalefulHarbinger/3d713bcf3acaaf9c8b059fa8a85976d7

Is there any further information I could try to find that might shed some light on this?

**Comment by TwistedGate** [comment]
Nah, tbh all the crashes point to the exact same thing still (even before and after the "hope-fix")

**Comment by BalefulHarbinger** [comment]
I noticed whenever I cause the crash its a dice-toss between whether the crash log reports an issue with the _client_ (which shows "Unexpected error") or the _server_ (which shows "Exception in server tick loop"). I know nothing about Java though, so I'm not sure if that's anything significant.

**Comment by TwistedGate** [comment]
It's still the same error. Both ending with a `ConcurrentModificationException` pointed to the same line. (https://gist.github.com/BalefulHarbinger/3d713bcf3acaaf9c8b059fa8a85976d7#file-crash-2023-10-25_21-53-13-client-txt-L10)

**Comment by BalefulHarbinger** [comment]
Still doesn't fix it :(

**Comment by TwistedGate** [comment]
darn it.. honestly now im out of ideas

**Comment by TwistedGate** [comment]
What is it saying this time? Im hoping for something new this time honestly :T

**Comment by mindforger** [comment]
couldn't you replace the iteration loop around the remove call by a "removeAll" ?! but i don't see why iterating the "remove" list should cause an issue with the "napalm" list there in the first place, this pattern should work

napalmPositions.get(d).removeAll(toRemove.get(d))

PS: i see napalmlist getting extended every time but never see the unsued keys removed, smells like a potential waste of memory imho

**Comment by BalefulHarbinger** [comment]
> What is it saying this time? Im hoping for something new this time honestly :T

It unfortunately is the same as previous ones :/
https://gist.github.com/BalefulHarbinger/161f41257ab62e8ec7c5581811ffcb9f

**Comment by BalefulHarbinger** [comment]
IT WORKS!
![2023-11-01_19 20 50](https://github.com/TwistedGate/ImmersivePetroleum/assets/111066603/9ad88ee2-7098-4ae6-9322-385e9553d4f6)

**Comment by BalefulHarbinger** [comment]
IT WORKS!
![2023-11-01_19 20 50](https://github.com/TwistedGate/ImmersivePetroleum/assets/111066603/af2c2785-5da5-4fac-bea5-31036e175f0e)

**Comment by TwistedGate** [comment]
Oh thank god
