### ISSUE TITLE
Survey Tool coordinates incorrect for deposits

### ISSUE THREAD

**Issue by cdeath-zz** [TwistedGate/ImmersivePetroleum#173]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.3-167

### Immersive Petroleum Version

4.2.0-26

### Current Behaviour

Using the survey tool shows deposits with coordinates.  When going to those coordinates, the deposit is not there.  If going in the opposite direction of those coordinates from the survey tool, the deposit is found.  It appears that the map visually is correct, but the coordinates are backwards.

### Expected Behaviour

The coordinates listed in the survey map show the location of the deposit.

### Reproduction Steps

Use the survey tool as normal.
Receive survey map.
Travel to coordinates of deposit.
Use survey tool to verify deposit but nothing found.
Travel to approximate location as per the visual representation on the survey map (roughly opposite direction of coordinates)
Use survey tool to find deposit as expected originally.

### Debug Crash Log

https://pastebin.com/AcvtqaJt

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Looked at it and found a much bigger issue, still related tho
