### ISSUE TITLE
[Suggestion] Allow for the creation of infinite reservoirs across all Minecraft versions

### ISSUE THREAD

**Issue by Delfite** [TwistedGate/ImmersivePetroleum#175]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

This suggestion applies mainly to 1.12.2, as I'm currently working on a modpack that uses Immersive Petroleum as a means to get infinite fluids at the cost of high power consumption and requiring you be in the correct biome, but it would also be great to have this across all Minecraft versions. Currently, setting `min_mb_fluid` or `max_mb_fluid` to `-1` just crashes the game instead of making the reservoir infinite. I wouldn't imagine this feature being hard to implement, so I look forward to seeing it added in the near future.

If you're wondering why I'm on 1.12.2 and not a version like 1.19.2 then it's due to the fact that Immersive Technology hasn't been updated past 1.12.2 yet. In addition to that, there's also the fact that 1.12.2 has a better ore dictionary system, has superior client-side and server-side performance, is easier to run on low-end systems compared to more modern versions of the game, and the 1.12.2 version of Thermal Foundation being SIGNIFICANTLY more feature-rich for configuring ore generation compared to its modern counterpart, which has next to no configurability.

**Comment by TwistedGate** [comment]
First of 1.12.2 is out of Support for a long time, aint gonna touch that anymore.

And setting `min_mb_fluid` and/or `max_mb_fluid` to `-1` is not the way. Instead set the `Depleted Fluid Yield` to something other than `0`. (That effectively sets the reservoir(s) to infinite)
See how the water reservoir does it.

https://github.com/TwistedGate/ImmersivePetroleum/wiki/1.12.2-1.1.10-&-Older#fluid-reservoirs there is even a wiki for this
