### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sephiroth91** [TwistedGate/ImmersivePetroleum#176]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

Hello :), I would like to upgrade my server from 1.18 to 1.20, but we are big fans of immersive petroleum and we don't want to do it without it. Therefore, I wanted to ask whether an update to 1.20 is planned in the near future or whether it will take even longer?

**Comment by TwistedGate** [comment]
Once things are stable with NeoForge yeah.

Also thanks for not using this template for the intented way.

**Comment by geferon** [comment]
It seems like the 1.20.1 NeoForge version is stable?
