### ISSUE TITLE
Can't find out any crude oil area.

### ISSUE THREAD

**Issue by willis1030** [TwistedGate/ImmersivePetroleum#178]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.3-167

### Immersive Petroleum Version

ImmersivePetroleum-1.19.2-4.2.0-28

### Current Behaviour

Using mineral survey tools and core sample drill can't find out any crude oil, nether water and lava.
Is anything wrong?

### Expected Behaviour

I think it should be there, but none.

### Reproduction Steps

just try and try...

### Debug Crash Log

no

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by voidsong-dragonfly** [comment]
Fluid reservoirs are not found using the core sample drill in 1.19.2. Please read the manual for the method to locate reservoirs.

**Comment by Mack18201991** [comment]
Vibration wave detectors should be used instead of core drilling
