### ISSUE TITLE
[Suggestion] Version for 1.20

### ISSUE THREAD

**Issue by Radon8472** [TwistedGate/ImmersivePetroleum#182]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

It would be nice if you could make a realse of this mod for minecraft v 1.20.

We are currently building a modpack for 1.20.1 and realy would like to include this mod.
The best would be if you could make a releasy for Classic Forge and maybe NeoForge as well

**Comment by PTALTS-LK** [comment]
1.20.1 is also a popular version with many mods, isn't it?
