### ISSUE TITLE
"No Bedrock" Setting for Derrick/Pumpjack

### ISSUE THREAD

**Issue by darkmage0707077** [TwistedGate/ImmersivePetroleum#183]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

I would like to request that a toggle be added to the config of Derricks and/or Pumpjacks that allows them to be used in Skyblock worlds, or any other world without a Bedrock layer - and therefore, Reservoirs - in it.

Ideally, it would cause them to generate a Reservoir on the blocks directly underneath when you build one over valid "natural" tiles (Dirt, Cobblestone, Stone, etc). Each one built would decrease the total number of Reservoirs allowed to generate in that chunk, with a config setting denoting how many max can spawn (0 allows unlimited).

Yes, players could build multiple Derricks/Pumpjacks next to each other to have many Reservoirs to draw from, but space management tend to be most of the challenge of Skyblock maps anyway, so I see it as more of a tradeoff. And they'd still have to build new ones over time, as well.

If there is such a setting or configuration, I'd like to suggest adding it to the README and/or FAQs section of the Wiki.

**Comment by voidsong-dragonfly** [comment]
IE mineral veins do not generate in skyblocks. IP fluid reservoirs are no different - they generate with worldgen and are innately a part of worldgen that does not make sense to separate from their generation context. No, we will not be adding a method of somehow acquiring reservoirs in skyblock packs.

**Comment by Mack18201991** [comment]
> IE 矿脉不会在天空街区中生成。IP 流体储层也一样 - 它们与世界生成一起生成，并且天生就是世界生成的一部分，与它们的生成环境分离毫无意义。不，我们不会在天空街区包中添加以某种方式获取储层的方法。

Can I understand that IE and IP do not support Sky Island maps?
