### ISSUE TITLE
Pumpjack not working at all

### ISSUE THREAD

**Issue by Itsyaboyyons** [TwistedGate/ImmersivePetroleum#186]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2

### Immersive Petroleum Version

1.19.2

### Current Behaviour

It does not work at all even if I do put like some sort of energy(creative accumulator for example) to input. It never happened before a few months ago, I don't know why it's happening now. Also, I am on a Mac so maybe it has something to do with it.
<img width="1440" alt="Screen Shot 2024-05-18 at 11 24 55 AM" src="https://github.com/TwistedGate/ImmersivePetroleum/assets/170190847/e321ce58-ad10-4021-bbbc-462e3ae7945d">

### Expected Behaviour

It expected it to actually work, pumping reservoirs so I can use it in my worlds.

### Reproduction Steps

1. First I projected the pump jack
2. I used the hammer to build the multi block 
3. I put the creative accumulator on the orange dot(for energy input,it didn't function)

### Debug Crash Log

I don

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Putting 1.19.2 in the `Immersive Engineering Version` and `Immersive Petroleum Version` is not whats being asked there.

---
Look at the achievements, they're a guide.

and

![Read the Fucking Manual](https://cdn.discordapp.com/emojis/499559424864681994.png)  
You have skipped a step.

**Comment by Itsyaboyyons** [comment]
Sorry, I am new on GitHub(created yesterday) also I am on Mac. I accidentally submitted it when I was typing the other step.

**Comment by Itsyaboyyons** [comment]
It actually still doesn't work despite having it over the well the derrick drilled into

**Comment by TwistedGate** [comment]
Did the pressure die down completely? (No fountain of black goodness coming out of the well)
Is the head of the Pump *above* the well?
Do the Fluid Tanks, you are trying to put the oil in to, have enough space/are not full?
