### ISSUE TITLE
[Suggestion] 1.20.1, please read carefully.

### ISSUE THREAD

**Issue by kienerxyzzy** [TwistedGate/ImmersivePetroleum#190]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

Can you port to 1.20.1? I know there is #182 but why did you reject it? I would want this to be updated to 1.20.1 or if you don't update, please provide an explanation. That would be greatly appreciated.

**Comment by TwistedGate** [comment]
It was always my plan to skip 1.20.0 through 1.20.3 as it seemed like a good idea at the time with the Forge and NeoForge split happening.
To mainly avoid the whole spiel with Forge and NeoForge mods at some points being somewhat compatible, which would cause me headaches. (The things i have seen in the IE Discords also put me off of the idea of making 1.20 to 1.20.3 releases)

Im in the middle of the 1.20.4 Port right now (See [Here](https://github.com/TwistedGate/ImmersivePetroleum/tree/1.20.4)) after having had some trouble IRL too which delayed it *a lot* and im waaay too deep to make 1.20.1 worth it anymore. (also just too much time has passed already)

And with 1.21 already being a thing, its only a matter of time before i have to *again* port this mod to that (or some other version) to keep up.
Im just a single person maintaining this with the help of @voidsong-dragonfly and a few others *every now and then*, which doesnt make it easy to support *many* versions in quick succession.


PS: I've been up for 19+ hours so if something doesnt make sense that is entirely on me lol

**Comment by kienerxyzzy** [comment]
Ok, so I'll wait for 1.20.4/1.21

**Comment by MehanikTMYT** [comment]
will wait for 1.21.1 instead of 1.21

**Comment by emanuele246gi** [comment]
The thing is that the vast majority of mods are on 1.20.1...
