### ISSUE TITLE
Suggestions on pipes disguised by scaffolding

### ISSUE THREAD

**Issue by Mack18201991** [TwistedGate/ImmersivePetroleum#193]
### Does this suggestion already exist?

- [x] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

1.Change the disguised scaffolding pipeline into complete blocks so that some "harsh characteristic" blocks can be placed above (such as redstone, bamboo scaffolding)
2.Additional but customizable feature: adding the original bamboo scaffold to the scaffold label, allowing the bamboo scaffold to support camouflage pipes

**Comment by TwistedGate** [comment]
The pipes are from Immersive Engineering and not Immersive Petroleum.
