### ISSUE TITLE
[Suggestion] Add config options to create infinite reservoirs for 1.16.5

### ISSUE THREAD

**Issue by alexkurbiel** [TwistedGate/ImmersivePetroleum#194]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

Hi, would it be possible to add the same config options that exist for 1.12 to 1.16.X, so that reservoirs can be configured to be infinite? Thanks for your consideration!

**Comment by TwistedGate** [comment]
Done via DataPacks <https://github.com/TwistedGate/ImmersivePetroleum/wiki/1.16.5-3.3.0#fluid-reservoirs>
