### ISSUE TITLE
[1.16.5] No motorboat

### ISSUE THREAD

**Issue by Kinsogu** [TwistedGate/ImmersivePetroleum#20]
**Description of the issue**

There is no motorboat.

**Versions and Modlist**

ImmersivePetroleum-1.16.5-3.2.0-3
Valhelsia 3 - 3.3.1 for MC 1.16.5 Modpack

**Comment by TwistedGate** [comment]
will be back next release #10

Check closed issues first

**Comment by Kinsogu** [comment]
"will be back next release #10"
