### ISSUE TITLE
[1.16.5] Distillation tower can´t be build

### ISSUE THREAD

**Issue by Grofeggi** [TwistedGate/ImmersivePetroleum#22]
Hi,
I´ve discoverd a bug in the Enigmatica 6 modpack where the distillation tower can´t be build. I guess it´s the steel scaffolding slab wich isn´t recogniced correctly. In the manual the mod doesn´t recognize the steel scaffolding slabs even thoug I had them in the Hotbar. I´ve double checked my configuration and the only possible issue is the slab. If this is not an issue with the mod itself, I´ve also contacted the support of the modpack.
![Inked2021-05-13_21 24 24_LI](https://user-images.githubusercontent.com/84152917/118178415-32e37a80-b434-11eb-8008-240c62a3a284.jpg)

**Comment by TwistedGate** [comment]
You need the grated slabs now
