### ISSUE TITLE
[1.16] NullPointerException on singleplayer

### ISSUE THREAD

**Issue by gingershaped** [TwistedGate/ImmersivePetroleum#23]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.  
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.16] Distillation Tower Interaction Crash"

### Description of the issue
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
When starting a singleplayer world, the game crashes with two "Exception caught during firing event: null" and then a NullPointerException.

### Versions and Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*  
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with `F3 + C`.  
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
Version 3.2.0-3
Forge version 36.1.18

### Crash Log
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
Link: [crash report](https://gist.github.com/GingerIndustries/c236de07014b66115be035725527bb87)

### Screenshot(s)
Images say more than a thousand words, so if you are bad at explaining things like me, throw in some images to accompany the `What happend?` section above.  
(Perhaps you could even reference them in that section too)

**Comment by TwistedGate** [comment]
Update your Java 8 version and see if the crash still happens.

You're using `1.8.0_51` which is stupid old (try `1.8.0_271` or higher)

**Comment by mindforger** [comment]
I would take a swing at bluemap, try to remove it, that crash is a bit unlikely to be caused ne an old java version, die exception indicates a mod interaction bug and mapping tools are known to interfere with World data

**Comment by TwistedGate** [comment]
Alright, well.. nothing i can do then? =P

**Comment by gingershaped** [comment]
Sorry for late response, neither of those fixes worked.
