### ISSUE TITLE
Mod Crashes on New Immersive Engineering Release 

### ISSUE THREAD

**Issue by ModernGamingWorld** [TwistedGate/ImmersivePetroleum#24]
- Clean up the API (Malte)
    - THIS IS A BREAKING CHANGE!
    - Don't expect addons to work without being updated!
https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/3326143

**Comment by ghost** [comment]
Here's a crash log and more information that will hopefully prove helpful:

Minecraft 1.16.5
Forge 36.1.24
ImmersiveEngineering-1.16.5-5.0.0-135
ImmersivePetroleum-1.16.5.3.2.0-3
immersiveposts-1.16.5-4.0.0
jei-1.16.5-7.7.0.100
Crash log: https://pastebin.com/fqszkbbq

**Comment by ModernGamingWorld** [comment]
yeah I did not have a crash log, so thanks @SonicSpeedster16
