### ISSUE TITLE
[1.16] No Gui and broken recipe for sulfur recovery unit

### ISSUE THREAD

**Issue by MuteTiefling** [TwistedGate/ImmersivePetroleum#31]
### Description of the issue
Simply put, the SRU forms, but there doesn't appear to be a gui for it at all. I'm also seeing a warning from KubeJS about the recipe as well
![image](https://user-images.githubusercontent.com/9543430/120197477-f9aa5900-c1ee-11eb-8e43-92188f057c9a.png)

Note: I did try overriding the recipe with KJS, but the warning was occurring prior to any modifications. It's as if the default recipe isn't handled properly?

### Versions and Modlist
ImmersiveEngineering-1.16.5-5.0.0-135
ImmersivePetroleum-1.16.5-3.3.0-4
Forge 36.1.16
unrelated Crash log for the rest: 
[crash-2021-03-31_23.03.54-server.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/6570344/crash-2021-03-31_23.03.54-server.txt)

### Crash Log
No Crash
[latest.log](https://github.com/TwistedGate/ImmersivePetroleum/files/6570408/latest.log)

**Comment by TwistedGate** [comment]
It having no GUI is intentional, it's a simple enough machine to not need one.

That recipe thing however is worrying, i'll look into after my break (this update took a toll on me)

**Comment by Royal-Jelly** [comment]
I too am also having problems with creating new recipes, I'm fairly sure that somethings up with the recipe handing.

I used custom events recipe handler from Kubejs, it doesn't complain about formatting ... however it silently fails and no recipe is registered. A properly formatted datapack style recipe also doesn't appear to work though, this one either errors in the console or also silently fails for no apparent reason.

It is very possible that KubeJS may not being able to parse your recipes, If that is the case maybe this whole issue can be fixed with a custom kubejs plugin.

**Comment by zzells** [comment]
I'm having a problem with the sulfur recovery not working despite power and fluid input and output being there in the right places. Is this bug in the mod? JEI registers the recipe for diesel just fine, so I'm unsure.

**Comment by TwistedGate** [comment]
Everything works with just IE, IP and a test datapack that adds a new recipe for tower, coker and hydro.

So im certain it's a KubeJS thing, not IP

**Comment by TwistedGate** [comment]
> A properly formatted datapack style recipe also doesn't appear to work though, this one either errors in the console or also silently fails for no apparent reason.

As for this, did you put the datapack in the `world/datapack` folder and not the `minecraft/resourcepack` folder? =P

**Comment by MuteTiefling** [comment]
For what it's worth, when I'm injecting a recipe with kubejs, it's just making a json file and loading it like any other data pack.

Also, bear in mind that the error shown originally was with no such recipes added.

**Comment by Royal-Jelly** [comment]
Yeah after fiddling I managed to get it working. It is most kefinitely on Kubjs's side for throwing those errors

**Comment by callmejay758** [comment]
Can OP share their modification file? I'm trying to fix this log error as well.

**Comment by TwistedGate** [comment]
Closing this because nothing seems to be happening.

Also GUI has by now been added (598527b3929d8a4f002e69bd35121dc8168d7422)

**Comment by MundM2007** [comment]
@TwistedGate The reason for this error `java.lang.IllegalArgumentException: Unexpected json object` seems to be that kubejs doesn't correctly detect the chance in the output item for destillation and hydrotreating, which create this error if the chance is not given. This also applies to adding recipes, which confused me at first, cause this value shouldn't be required. My suggestion would be that you make the chance value optional and default to 1.0. Another question: Why does every fluid input and Coker's output require a tag?
