### ISSUE TITLE
[1.16.5] Portable "free Energy" Generator 

### ISSUE THREAD

**Issue by bluefire-fx** [TwistedGate/ImmersivePetroleum#32]
### Description of the issue
The Portable Generator, simply put, is a free energy device. While it technically interacts correctly with fluid pipes, consumes gasoline, stalls when a redstone signal is applied and overall works, looks and sounds very nice since the last update, it outputs its 255 flux/t at all times instead off only when its running on gas. Just placed it in a fresh superflat world with just Forge, IE and IP, connect to a capacitor and it started outputting energy all by itself without fuel. (as shown on screenshots). Tested with both latest and recommended Forge.

### Versions and Modlist
<ul>
<li>ImmersiveEngineering-1.16.5-5.0.0-135</li>
<li>ImmersivePetroleum-1.16.5-3.3.0-4</li>
<ul>
<li>Forge 36.1.24 (latest)</li>
<li>Forge 36.1.0 (recommended)</li>
</ul>
<li>java openjdk 1.8.0_292</li>
</ul>

### Crash Log
- did not crash

### Screenshot(s)
![empty](https://user-images.githubusercontent.com/85301726/120683229-a873c100-c49d-11eb-930e-dcc30a0200db.png)
![free_energy](https://user-images.githubusercontent.com/85301726/120683368-d35e1500-c49d-11eb-98cd-719059984eb5.png)

**Comment by LobaCW** [comment]
I have the same issue, took me a while to notice this, but it broke all my oil power generation, I came here to report but glad it's already been posted before.
Please can you devs take a look into this? i appreciate it

**Comment by sadlyalive** [comment]
I also discovered that my batteries kept receiving energy despite my portable generators having no access to gasoline. This should probably be a top-priority bug since it's a blatant cheat in most servers that use the mod.
