### ISSUE TITLE
[Suggestion] Make fuel fluid more lethal while using as weapon

### ISSUE THREAD

**Issue by MasterIMLG** [TwistedGate/ImmersivePetroleum#35]
Naplam has impressive performance in ground warfare isn't it?
If I may suggest, would you please to add something like... Naplam bomb? As an C.o.D Player, it would be fascinating to recreate the scene of a Naplam Strike.
Or in another way, make these fuel fluid more configurable while spraying by using chemical thrower, 
such as can custom how many levels of "Flammable" or "Slippery" the naplam and lubricant can give to hit entity,
or if naplam sprayed from chem-thrower can set blocks on fire/burn down ignitable blocks fairly quick.

**Comment by TwistedGate** [comment]
> can set blocks on fire/burn down ignitable blocks fairly quick.

Basicly what the molotov will now do in the future.
