### ISSUE TITLE
[1.16.5] Translation problem and text mismatch

### ISSUE THREAD

**Issue by FrannDzs** [TwistedGate/ImmersivePetroleum#36]
### Description of the issue
Hi, I am the Spanish translator for this mod, I have 2 problems, the first one is that the lightning rod is not shown translated in the projector list, and the second one is that there is a text offset problem in a table of the engineer's manual, precisely in the distillation tower, at the end of the document. This problem also appears in the English version of the mod.

### Version
ImmersivePetroleum-1.16.5-3.3.0-4

### Screenshot(s)
1st problem:
![error](https://user-images.githubusercontent.com/76663897/123004210-af9a3a80-d38a-11eb-9e27-1b0d68f5ecf6.png)

2nd problem:
![error2](https://user-images.githubusercontent.com/76663897/123004245-bc1e9300-d38a-11eb-836a-54cf26469ee3.png)

**Comment by TwistedGate** [comment]
First problem apears to be a misshap in the spanish translation file in IE

see https://github.com/BluSunrize/ImmersiveEngineering/blob/1.16.5/src/main/resources/assets/immersiveengineering/lang/es_ec.json#L324

the string on the left shouldnt have been edited, yet it still has been anyway

As for the second i think it's also an IE thing

**Comment by FrannDzs** [comment]
Thank you for your response! I will ask Blusunrize maybe he knows something. greetings!

**Comment by TwistedGate** [comment]
All of these are now fixed.

**Comment by FrannDzs** [comment]
> All of these are now fixed.

Thanks!
