### ISSUE TITLE
[1.16.5] Immersive Petroleum multiblocks don't output to Create pipes

### ISSUE THREAD

**Issue by Koku0** [TwistedGate/ImmersivePetroleum#42]
### Description of the issue
IP  multiblocks (coker, pumpjack, distillation tower) don't output to Create pipes, even with a mechanical pump going. These same multiblocks output to IE pipes (with or without a pump) and receive input from Create pipes fine (with or without a pump), while IE machines input and output fine with Create pipes.
It's just the IP multiblocks and outputting to Create pipes that is the problem.

### Versions and Modlist
Minecraft: 1.16.5
Forge: 36.2.2
IE: 5.0.2-137
IP: 3.3.0-5
Create: 0.3.2

**Comment by Koku0** [comment]
Upon further testing, IP multiblocks output to Create tanks that are immediately adjacent to the fluid output port.

**Comment by TwistedGate** [comment]
Creates pump works on the tower output, but it greatly hinders the towers ability to output all fluids in a timely manner. Even with the pump.
