### ISSUE TITLE
Can't open book, your mod is mentioned with IE, here's the logs

### ISSUE THREAD

**Issue by MrTubzy456** [TwistedGate/ImmersivePetroleum#50]
I went to open my Immersive Engineering book and can't. Something failed to load. It said to report the issue, but I looked and notice that this Immersive Petroleum is mentioned in the logs so maybe it's an issue there. Here's the logs: https://mega.nz/file/w1lkXYoB#6ZUgWIBEUiUNv1z7oPrUaVFVC5U98yBwkYUFOAqQRQ8

**Comment by TwistedGate** [comment]
Update Immersive Posts and Immersive Petroleum
