### ISSUE TITLE
[1.16.5] Server crashed because ConcurrentModificationException

### ISSUE THREAD

**Issue by 0XPYEX0** [TwistedGate/ImmersivePetroleum#53]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.  
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.16] Distillation Tower Interaction Crash"

### Description of the issue
An error occurred when the server started, and it could not be started.
I guess this may caused by List is out of sync caused by asynchrony ? idk...

### Versions and Modlist
Minecraft: 1.16.5
ImmersiveEngineering: 5.0.0-135
ImmersivePetroleum: 3.3.0-4
ModList: Following the crash report

### Crash Log
https://paste.ubuntu.com/p/tnnhpn6577/

### Screenshot(s)
Images say more than a thousand words, so if you are bad at explaining things like me, throw in some images to accompany the `What happend?` section above.  
(Perhaps you could even reference them in that section too)

Thanks for your reply!!!

**Comment by TwistedGate** [comment]
Please update to 3.3.0-6 and see if the crash persists there

**Comment by 0XPYEX0** [comment]
I deleted some mods:
ClientTweaks
drippyloadingscreen
fancymenu
konkrete
performant
ponderjs
shutupexperimentalsettings
Tips

And it works well now...
Maybe they have a conflict?
These are some mods that should only be loaded in Client, I put them to Server wrongly

**Comment by 0XPYEX0** [comment]
It crashed again, and I try to use ImmersivePetroleum-3.3.0-6, it crashed too:
https://paste.ubuntu.com/p/VbrygcqyzD/

**Comment by mindforger** [comment]
the source(meaning the offending object in world) of both crashes seems unrelated, the later one happened while spawning something from IP in the nether while generating a new chunk

**Comment by 0XPYEX0** [comment]
They all happen when the server is starting

**Comment by mindforger** [comment]
did you change/update/replace/add a mod recently?

**Comment by 0XPYEX0** [comment]
Just delete the mods that should only be loaded in Client,and update ImmersivePetroleum to 3.3.0-6

**Comment by mindforger** [comment]
the second crash report went off by some data fixer and that is why it might be unrelated to the first crash 
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

this seemed to stem from kubejs, i suppose their data data fixer interaction is broken too ...

**Comment by 0XPYEX0** [comment]
So...What can I do...?

**Comment by 0XPYEX0** [comment]
I got a new one:
https://paste.ubuntu.com/p/PSbJMxp384/
