### ISSUE TITLE
CRASH ON STARTUP: Immersive Petroleum NoSuchMethod error with latest release of Immersive Engineering

### ISSUE THREAD

**Issue by Cynix32** [TwistedGate/ImmersivePetroleum#55]
### Description of the issue
Latest curseforge release of Immersive Engineering breaks Immersive Petroleum
Based on the crashlog, it probably has something to do with this change
- Reduce block updates on multiblocks (Malte)

### Versions and Modlist
Forge 36.2.8
MC 1.16.5
Java 8
[ImmersiveEngineering-1.16.5-5.0.4-139.jar
](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/3483884)
ImmersivePetroleum-1.16.5-3.3.0-6.jar

### Crash Log
https://pastebin.com/si9x5RMu

**Comment by Cynix32** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/d2233c36a73a998bdacb80aed5a4177e5ec9ab4d

May help with diagnosing the crash.

**Comment by drakray** [comment]
What I got was https://pastebin.com/0mbKPzH7
Error in modList is in Immersive Petroleum, but stack mention `corgiaoc.byg.client.textures.ColorManager.onItemColorsInit`
Mixin stuff maybe?, hope the log help

**Comment by ranenvious** [comment]
I am getting this as well. Not sure if its the same cause since I don't do modding, but the logs seem similar enough for me to think so.

**Comment by keydoch** [comment]
I believe I'm also having the same issue.

### Crash log:
https://pastebin.com/8xuNSTzj

**Comment by Sublime204** [comment]
I updated Immersive Engineering this morning as well and got the same crash loading MC after that. I rolled back to the old version of Immersive Engineering for now and it's working.

**Comment by BedrockLegends** [comment]
The same crash that we just got yesterday

**Comment by Pepelespooder** [comment]
Not sure if its related but even using a Lower version for me I'm getting a crash
[Immersive Petrol.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/7312043/Immersive.Petrol.txt)
Remove Immersive petrol and the crash is gone
its mentioning Sodium? so im guessing its a halogen incompatibility?
---edit---
Figured it out I think , Immersive Petroleum Any version Is not Compatible With Immersive engineering The new version...

Anyone Experiencing my Version of the bug IT seems if you Downgrade immersive engineering to 5.0.3-138 and immersive petrol to 3.3.0-5 The crashes stop and the game loads normally

**Comment by TwistedGate** [comment]
> 
> 
> Not sure if its related but even using a Lower version for me I'm getting a crash [Immersive Petrol.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/7312043/Immersive.Petrol.txt) Remove Immersive petrol and the crash is gone its mentioning Sodium? so im guessing its a halogen incompatibility? ---edit--- Figured it out I think , Immersive Petroleum Any version Is not Compatible With Immersive engineering The new version...
> 
> Anyone Experiencing my Version of the bug IT seems if you Downgrade immersive engineering to 5.0.3-138 and immersive petrol to 3.3.0-5 The crashes stop and the game loads normally

Thats a completely different crash

**Comment by FrannDzs** [comment]
I have the same problem. Tested in several versions of JVM.

**Comment by adamhoheisel** [comment]
The latest version of `ImmersiveEngineering-1.16.5-5.0.4-139.jar` has created a breaking change in Immersive Petroleum.

If you are having crashing issues rolling back to `ImmersiveEngineering-1.16.5-5.0.3-138.jar` will work with `ImmersivePetroleum-1.16.5-3.3.0-6.jar` & `ImmersivePetroleum-1.16.5-3.3.0-5.jar`

@FrannDzs At this time JVM version should not matter.

**Comment by TwistedGate** [comment]
Fixed with #56

**Comment by ProsperCraft** [comment]
I came for the same problem, this fix not pushed to curseforge yet?

**Comment by DigitalData** [comment]
> I came for the same problem, this fix not pushed to curseforge yet?

Yeah, the last push to CurseForge was in September. Consider rolling back IE or removing IP until the fix is released.

**Comment by TwistedGate** [comment]
Release is out (3.3.0-7) closing this now.
