### ISSUE TITLE
[1.16.5] `distillationTower_energyModifier` config backwards from expectation

### ISSUE THREAD

**Issue by MuteTiefling** [TwistedGate/ImmersivePetroleum#58]
### Description of the issue
With Immersive Engineering, their configs are multipliers to the final cost. However, when I set `distillationTower_energyModifier` to 3 expecting the cost to go from 2048 to 6144, it instead dropped to 682. It's dividing by the config value, rather than multiplying. 

### Versions and Modlist
IE: ImmersiveEngineering-1.16.5-5.0.5-140
IP: ImmersivePetroleum-1.16.5-3.3.0-7
Forge: 36.2.4

### Crash Log
No Crash

### Screenshot(s)
![image](https://user-images.githubusercontent.com/9543430/139297942-35db2641-46c7-48b6-b230-2866d6d6d485.png)

**Comment by MuteTiefling** [comment]
Minor update. I've set it to `0.3333` and it's still at `2048` in game.

Same for `0.3`.

**Comment by TwistedGate** [comment]
Read the comment above the config option. (Comments start with `#`)

**Comment by MuteTiefling** [comment]
`#A modifier to apply to the energy costs of every Distillation Tower recipe, default=1`

Perhaps my English is failing me, but "modifier" gives me no suggestion which way it'll go. It could be taking the square, adding, or any other mathematical transformation.

Considering that this is an addon for IE, I think it's reasonable to assume it is a multiplier as that's what IE does in their configs.

 It also, unlike the others, says nothing about not accepting values below `1`.

`#A modifier to apply to the energy costs of every Distillation Tower recipe, default=1`
`distillationTower_energyModifier = 3.0`
`#A modifier to apply to the time of every Distillation recipe. Can't be lower than 1, default=1`
`distillationTower_timeModifier = 1.0`

Not accepting a smaller value here also immediately cuts people out of raising the cost. As it stands, one can only lower the cost, which may not always be desirable (and is not in this case).
