### ISSUE TITLE
reservoir get command throws error on dedicated server.

### ISSUE THREAD

**Issue by TiperX** [TwistedGate/ImmersivePetroleum#61]
"/ip reservoir get" uses a client only class.
Error message:
[Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER

**Comment by TwistedGate** [comment]
Follow the template and re-open with a proper report.
