### ISSUE TITLE
(1.16.5 Suggestion):vehicles

### ISSUE THREAD

**Issue by ghost** [TwistedGate/ImmersivePetroleum#63]
inspired by the motorboat i thought a few powered vehicles would be nice
these vehicles similarly to the boat and most IE tools would have multiple upgrades and upgrade slots.
i wont mention trains because these seem to be worked on by other mods.
first of all my main thought would be something like a bulldozer:basicly a large engine on threads that consume alot while being slow but can thru different upgrades be used to mine large amounts of blocks.for example attaching a drill infront of it would turn it into a mining device or adding chest would let it be a slow but very large drivable chest.

furthermore a car would be a faster vehicle to make exploration easier.

the upgrades i thought of would be different wells,chest as storage upgrades,tanks as fuel upgrades and engines to determine the fuel type

**Comment by TwistedGate** [comment]
Sorry, but apart from the Motorboat i don't ever intend on adding vehicles (land or air) in any way, shape or form.
Entites are a massive pain in the behind to deal with.
