### ISSUE TITLE
Feature Request: Waterlogging your Pumpjack?

### ISSUE THREAD

**Issue by Boolyman** [TwistedGate/ImmersivePetroleum#64]
Is there any way you could enable waterlogging on your multiblocks?  At least your pumpjack?  For underwater oil deposits, especially in a couple of my packs that take place underwater, it would be very nice if the player didn't see the odd waterwall textures.  I know it might not make 100% complete technical sense, but considering there is no mod that allows for "oil rig" type building, your pumpjacks are the only option for underwater oil.

**Comment by TwistedGate** [comment]
Just build a platform above water or perhaps even a small underwater base.

im not going to make the multiblocks waterloggable.
