### ISSUE TITLE
Java.lang.VerifyError: class (1.16.5-3.3.0-8)

### ISSUE THREAD

**Issue by anon1593** [TwistedGate/ImmersivePetroleum#69]
As title says latest version 1.16.5-3.3.0-8 crashes at startup.
issue started after I began updating mods.
Forge version: 36.2.20
Mod list is included in the crash log

[crash-2021-12-19_21.14.53-fml.txt](https://github.com/TwistedGate/ImmersivePetroleum/files/7742193/crash-2021-12-19_21.14.53-fml.txt)
[latest.log](https://github.com/TwistedGate/ImmersivePetroleum/files/7742197/latest.log)
![01](https://user-images.githubusercontent.com/24881009/146703189-58c01321-1d71-44e6-8486-963b453a956e.png)
.

**Comment by Trogdayton** [comment]
Alright, so not to be that guy, but I am having this same issue, and I'm fully updated on both mods. Ideas?

**Comment by Trogdayton** [comment]
Nevermind. I was going to say I was fully updated and having this issue still but the curseforge app isn't recognizing the 3.3.0.9 as the latest update, even though if you go into versions it shows up at the top. If you use the update button it goes to 3.3.0.8 jut FYI.
