### ISSUE TITLE
[1.16.5] Crash on load after Immersive Engineering update. java.lang.VerifyError: class flaxbeard.immersivepetroleum.common.blocks.tileentities.DistillationTowerTileEntity overrides final method shouldRenderAsActive.()Z

### ISSUE THREAD

**Issue by ProsperCraft** [TwistedGate/ImmersivePetroleum#70]
### Description of the issue
After the Immersive Engineering update today Immersive Pet crashes on load.

### Versions and Modlist

ImmersiveEngineering-1.16.5-5.0.6-141
ImmersivePetroleum-1.16.5-3.3.0-8
forge-1.16.5-36.2.22

### Crash Log
https://gist.github.com/ProsperCraft/506d698f9ef1688bd388da3694bb158a

**Comment by craeckor** [comment]
Mhh...

I think it's not a problem in the mod, because my friend also has this problem, but a day before he had the problem, it worked fine, we have not made any updates in that time

Try do delete the Mod an Reinstall it, and delete the Config (If the mod has any config)

**Comment by ProsperCraft** [comment]
I don't think you understand me clearly, Immerisve Engineering updated TODAY, which requires this mod to update to be compatible.

**Comment by Peca21** [comment]
Yep Same here the mod needs to be updated

**Comment by Vapaman** [comment]
This issue needs to be adressed asap.

**Comment by TwistedGate** [comment]
Already fixed #69
