### ISSUE TITLE
 Immersive Petroleum does not start with Immersive Engineering

### ISSUE THREAD

**Issue by TainanRezende** [TwistedGate/ImmersivePetroleum#71]
hi, i wanted to report that the current version does not start with the latest version of immersive engineering

EM version: ImmersiveEngineering-1.16.5-5.0.6-141

IMP version: ImmersivePetroleum-1.16.5-3.3.0-8.jar

**Comment by TwistedGate** [comment]
Follow template, also guessing #69 so already fixed.
