### ISSUE TITLE
[BUG]ImmersivePetroleum Cause Random Startup Crash

### ISSUE THREAD

**Issue by khjxiaogu** [TwistedGate/ImmersivePetroleum#73]
### Description of the issue
Sometimes start game would cause a startup crash. Restart would get everything fine.
Also get a same crash as #53 , but on client and in IP 3.3.0-7. It seems that this bug did not get fixed.
### Versions and Modlist
IE 5.0.5
IP 3.3.0-7
forge 36.2.4

### Crash Log
[crash-fml](https://paste.ubuntu.com/p/hgVfKpz8qB/)

**Comment by TwistedGate** [comment]
Definitely got fixed lmao

*Update IP to 3.3.0-8*

**Comment by khjxiaogu** [comment]
Nope, I don't think so. I am now using 3.3.0-8 but I reproduced this crash in my dev environment.

**Comment by TwistedGate** [comment]
You didnt even say you were in dev before? That would've been nice to know in the first place =P

**Comment by khjxiaogu** [comment]
> You didnt even say you were in dev before? That would've been nice to know in the first place =P

I reproduce it in both dev and normal client. I checked out the stack trace and found no change in IPMetalMultiblockBlock after 3.3.0-7, so I think this is not fixed. If you believe it's fixed, then it's fixed

**Comment by TwistedGate** [comment]
4df9af3d981eb05ee2b7e56ea97b1934b562252c
