### ISSUE TITLE
[1.16.5] java.lang.StackOverflowError: Ticking block entity 	at blusunrize.immersiveengineering.common.blocks.generic.PoweredMultiblockTileEntity.

### ISSUE THREAD

**Issue by ProsperCraft** [TwistedGate/ImmersivePetroleum#74]
### Description of the issue
Player on the dedicated server was making a distillation tower and the server locked up, it eventually crashed out with this crashlog.

### Versions and Modlist
forge-1.16.5-36.2.22
ImmersiveEngineering-1.16.5-5.0.6-141
ImmersivePetroleum-1.16.5-3.3.0-9

### Crash Log
https://gist.github.com/ProsperCraft/a7e200d248570ab2d3da2283e3ed93d8

Latest log-
https://gist.github.com/ProsperCraft/b615ea9426cfb790c27e470be7d19490

Debug log-
[debug.zip](https://github.com/TwistedGate/ImmersivePetroleum/files/7771799/debug.zip)

**Comment by ProsperCraft** [comment]
This is far worse then I thought- the server crashes on login now-
https://gist.github.com/ProsperCraft/bf595725f369fff198efa8a44bcdbf9f

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/a7d12de081b22a1fe839216f9a8d8a34

**Comment by xepps** [comment]
I've also got this issue and similar crash report. I'm using versions:
- forge-1.16.5-36.2.22
- ImmersiveEngineering-1.16.5-5.0.7-143
- ImmersivePetroleum-1.16.5-3.3.0-9
