### ISSUE TITLE
[1.16.5] [Visual bug] Gasoline is partially transparent in GUI's and tanks

### ISSUE THREAD

**Issue by Vapaman** [TwistedGate/ImmersivePetroleum#75]
### Description of the issue
Gasoline is partially transparent in GUI's of machines and tanks. Most noticable with Thermal's fluid cells and distillation towers.
### Versions and Modlist
ImmersiveEngineering-1.16.5-5.0.7-143.jar
ImmersivePetroleum-1.16.5-3.3.0-10.jar
forge-1.16.5-36.2.22-client.jar
forge-1.16.5-36.2.22-universal.jar
### Screenshots
![2021-12-24_19 31 55](https://user-images.githubusercontent.com/77460466/147367234-fcec3cd6-368d-4770-b1d4-ef6756f6cdb3.png)
![2021-12-24_19 37 22](https://user-images.githubusercontent.com/77460466/147367292-e79c39d1-f21a-45a6-b2ca-357b94e4999b.png)

**Comment by TwistedGate** [comment]
Known this for a while, but i can't do anything about, it's some weird rendering thing.

It does work in-world and IE Tank (to name a few examples)

Sure i could edit the texture such that the transparency is above the threshold, but up to a point it has worked without.
