### ISSUE TITLE
Game crash while the crusher is working wiith automatic lubricator. 1.16.5

### ISSUE THREAD

**Issue by kwaltersf46** [TwistedGate/ImmersivePetroleum#77]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.  
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.16] Distillation Tower Interaction Crash"

### Description of the issue

Crusher with lubricator IE , version140 IP Version  0-8 Worked as expected, I Upgraded to IE -143 and IP to -10  and when I added item into the crusher it just crashes goes to saving world and sits. I have to end tack.

I downgraded back to 140 and 0-8 and removed the lubricator.

I then put IE -143 and IP -10 back in restarted game, added Items to the crusher everything works as expected.  

### Versions and Modlist

Crash report attached.

Forge -1.16.5.36.22
jei 1-16.5-7.7.1.139
OreExcavation 1.8.157
ImmersiveIndustry 1.16.5c - have not used it in the world yet.
JourneyMap 5.7.3

### Crash Log

https://pastebin.com/i2jUp391

### Screenshot(s)

Starts with a black screen and then crashes.

**Comment by TwistedGate** [comment]
From the crash
`Failure message: Mod immersivepetroleum requires immersiveengineering 1.16.5-5.0.6-141 or above Currently, immersiveengineering is 1.16.5-5.0.5-140`

And you were using IP `3.3.0-9`

So install IE `5.0.6-141` and IP `3.3.0-10` and you should be golden.

**Comment by kwaltersf46** [comment]
"So install IE 5.0.6-141 and IP 3.3.0-10 and you should be golden."  Done.

Same result crashed as soon as I replaced the oiler and dropped an item in the crusher.

https://pastebin.com/ALSQ90jY

After I deleting the oiler with IE 5-140 and IP 3.8-8. I reinstalled 7-143 and 3.3.0-10 with out oiler and it plays fine .

**Comment by brisingraerowing** [comment]
Twisted, I noticed you mentioned this being confusing on Discord. Looking at the code, this seems to be a minor race condition where the process queue empties before the lubricate handler gets the item in process. Not exactly sure how to fix it, though. Possibly just using a try-catch block.
