### ISSUE TITLE
[1.12.2] Error in Russian language file

### ISSUE THREAD

**Issue by K14Mua** [TwistedGate/ImmersivePetroleum#79]
Text from English file

chat.immersivepetroleum.info.coresample.oil=%s mB %s
chat.immersivepetroleum.info.coresample.noOil=No Fluid Reservoir
chat.immersivepetroleum.info.coresample.oilRep=Up to %d mB/tick of trace %s

Text from Russian file

chat.immersivepetroleum.info.coresample.oil=%s мВ нефти
chat.immersivepetroleum.info.coresample.noOil=Нет нефти
chat.immersivepetroleum.info.coresample.oilRep=До %d мВ/тик %s

Due to this bug, oil is displayed EVERYWHERE in the game. Even if in fact there is water or lava.

**Comment by TwistedGate** [comment]
Sorry but i've dropped support for 1.12.2 a looong time ago.

**Comment by K14Mua** [comment]
> Sorry but i've dropped support for 1.12.2 a looong time ago.

There are modpacks that still use this version of the mod.
