### ISSUE TITLE
Custom Distillation Tower recipes cause a client-side crash when connecting to server 1.16.5

### ISSUE THREAD

**Issue by benjaming20** [TwistedGate/ImmersivePetroleum#84]
This issue has existed for some time, and for many updates. The issue occurs when editing the mod file to add custom distillation recipes to the data directory to both a server and a client on the same version and then attempting to join the server, which will cause the client to crash after a 2nd unsuccessful attempt. 

I can confirm the issue is indeed a bug as the custom recipes are completely valid as they work fine on singleplayer worlds. Moreover, this identical modifcation when applied to Immersive Petroleum version ImmersivePetroleum-1.16.5-3.3.0-8.jar or older will not reproduce this issue with the same custom recipes. (Immersive Engineering must be downgraded to version ImmersiveEngineering-1.16.5-5.0.5-140 for this version I believe.) I AM DEFINITELY ADDING THE RECIPES TO BOTH THE SERVER .JAR FILE AND CLIENT .JAR FILE.

I cannot get crafttweaker to work properly with creating distillation tower recipes, but I have been able to get crafttweaker to make reservoirs, so I am unsure if it is incompetence on my part or if crafttweaker functionality is also broken with distillation tower recipes. Despite this your mod is excellent and I am still having a hell of a time on the older version, I'd just love to see this fixed so I can finally update both IP and IE to their latest versions. Thanks!!

**Comment by TwistedGate** [comment]
- [x] Didnt follow the old Template.
- [x] Edited the Jar File.
- [x] Self-Confirmation

All of these invalidate this, do i need to say more?
