### ISSUE TITLE
[1.16.5][BUG] IP List Command Not Found

### ISSUE THREAD

**Issue by 0xIkari** [TwistedGate/ImmersivePetroleum#89]
### Is there an existing issue for this?

- [X] Yes, i have searched for already existing issues.

### Are you using the most recent version of X?

- [X] Yes, i am using the most recent version.
- [X] Yes, it still happens in the most recent version.

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Immersive Engineering Version

3.3.0-11

### Related Mods and their Versions

CraftTweaker-1.16.5-7.1.2.511
ContentTweaker-1.16-1.0.0.develop.36

### Current Behaviour

Immersive Petroleum Indicates that one should enter /ip reservoir list to get a list of reservoirs, but no such command exists.

![image](https://user-images.githubusercontent.com/30129546/177537803-da73adb3-e9dc-4b3a-a0ff-5e83f84f964b.png)

### Expected Behaviour

A list of all reservoirs should be provided to the player.

### Reproduction Steps

Create a custom reservoir using ContentTweaker script

new mods.immersivepetroleum.ReservoirBuilder(<fluid:minecraft:water>, 9999999, 9999999, 9999999, 50)
	.addDimensions(false, ["overworld"])
	.build("Lava But Not");

Attempt to run /ip reservoir list

### Logs

n/a

### Additional Informations

* Add a thumbs-up to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ghost** [comment]
not reproduceable / invalid report - please add IE version
3.3.0-11 is the IP version
also your CT-line looks wrong
according to the wiki there're two errors
1) `ReservoirBuilder(fluid:minecraft:water, 9999999` - should be `ReservoirBuilder(<fluid:minecraft:water>, 9999999` - you missed the angle brackets
2) `addDimensions(false, ["overworld"])` - should be `addDimensions(false, ["minecraft:overworld"])` - you missed the minecraft tag
please fix the errors and add IE version so others can test it

**Comment by TwistedGate** [comment]
> not reproduceable / invalid report - please add IE version
> 3.3.0-11 is the IP version

*No it's not, that's still on me to decide.*
I forgot to add the option to add the IP version aswell, and for this one i can ignore it. (i'll fix that at some point.)

Rest of your comment is valid though.

Aaaaanyway
---
Yeah that's a leftover thing i forgot to remove.
`/ip reservoir list` has been nuked in favour of using the auto-complete function of commands. (Pressing TAB)

As you can just select it when entering `/ip reservoir set` and then pressing Tab.

**Comment by ghost** [comment]
> > not reproduceable / invalid report - please add IE version
> > 3.3.0-11 is the IP version
> 
> _No it's not, that's still on me to decide._ I forgot to add the option to add the IP version aswell, and for this one i can ignore it. (i'll fix that at some point.)

alter ... ey echt jetzt? ich sollte github echt boykottieren ... alle die gleiche scheiß einstellung - altis life - minecraft - selbst die luschen von google und twitch die es nich packen mit ihren ach so umfangreichen auto-code tools codes generieren zu lassen die jeder anfänger besser drauf hat
wenn ihr die hilfe der community nich wollte dann lasst es - aber straft nich die ab die ihre freizeit genau wie ihr dafür nutzen reports drauf zu prüfen ob diese überhaupt valid/sinnvoll sind
fakt: warum auch immer fehlt die pflicht-info der IE version - und wenns n fehler in der vorlage war - naja, dann hätte man sich als jemand der seinen report ernst meint auch die mühe machen können sowas mit reinzupacken wie "konnte ich nich auswählen - daher hier: v.XXX"

**Comment by 0xIkari** [comment]
> not reproduceable / invalid report - please add IE version 3.3.0-11 is the IP version also your CT-line looks wrong according to the wiki there're two errors
> 
> 1. `ReservoirBuilder(fluid:minecraft:water, 9999999` - should be `ReservoirBuilder(<fluid:minecraft:water>, 9999999` - you missed the angle brackets
> 2. `addDimensions(false, ["overworld"])` - should be `addDimensions(false, ["minecraft:overworld"])` - you missed the minecraft tag
>    please fix the errors and add IE version so others can test it

The issue in question was not related to the CT code, but I included it for completion.
I copy and pasted my code from my editor, and I guess it ate the < >.
The dimension tag is wrong, thank you for letting me know. 
The IE version wasn't related to the issue, it was purely a command error response I was raising to their attention.

**Comment by TwistedGate** [comment]
See 04f204ea3dee8127e03387bc20d1763e0b6a8458
