### ISSUE TITLE
my game will not load if i have the mod instaled it just crashs

### ISSUE THREAD

**Issue by redbike02** [TwistedGate/ImmersivePetroleum#91]
### Minecraft Version

1.16.5

### Immersive Engineering Version

5.1.0-148

### Immersive Petroleum Version

3.4.0-12

### How did it happen?

when ever i try and load minecraft, the game starts to load then goes back to the launcher ang gives me a crash report

### Crash Log

https://gist.github.com/redbike02/2d6eb8402138852f74b43a307c7aca02

**Comment by TwistedGate** [comment]
Did you edit the `immersivepetroleum-common.toml`? If so, delete and let IP regenerate that.

**Comment by redbike02** [comment]
i just downloaded that version and put it in my mods folder i dont edit the mod at all or change config files. also i dont know much on computers

**Comment by brisingraerowing** [comment]
`Java Version: 1.8.0_51, Oracle Corporation`

There's a likely cause. Update Java. I recommend using the [Adoptium Project](https://adoptium.net/temurin/releases?version=8).

Also, `ImmersivePetroleum-1.16.5-3.4.0-12 (4).jar`. What's with the `(4)`? Make sure you don't have multiple instances of the mod. Forge has some very weird issues with that in newer versions.

**Comment by redbike02** [comment]
ok i will try fit that now sorry for any inconvenience

**Comment by redbike02** [comment]
i am really sorry about this but i dont know how to install this properly

**Comment by brisingraerowing** [comment]
On that site, select `Windows` in the `Operating System` dropdown, `x64` in the `Architecture` dropdown, and `JRE` in the `Package Type` dropdown. Leave the `Version` dropdown at `8`. Then click the button to the right that says `.msi`, and save the file somewhere.

After the file is downloaded, use File Explorer to find it and then double click it to initiate the installation. You'll have to tell the launcher to use the new install, and that process varies depending on which launcher you're using.

**Comment by redbike02** [comment]
i have downloaded the file and installed it but i dont know how to change the installation i am using the official minecraft launcher

**Comment by TwistedGate** [comment]
Go to your instances..
![a](https://user-images.githubusercontent.com/31029668/179441926-4f7a3856-0e33-4f62-a607-0a36cabbb7a9.png)

---
1\) Click the `...` Button.
2\) Click the `Edit` Button.
![b](https://user-images.githubusercontent.com/31029668/179441924-3fb389e3-7b0f-44bd-8ee8-9c675cb08a68.png)

---
1\) Click the `More Options` Button.
2\) Click the `BROWSE` Button where it says `JAVA EXECUTABLE`.
![c](https://user-images.githubusercontent.com/31029668/179442113-7a7d9983-e1c5-4144-bc1c-74ffa9295986.png)

Now go to where you have your java version installed that you've downloaded and find `...\bin\javaw.exe`, select it and hit enter.

That should it be done.

**Comment by TwistedGate** [comment]
Marking this as done.
