### ISSUE TITLE
Pumpjacks won't output to fluid pipes [USER ERROR, not a bug]

### ISSUE THREAD

**Issue by MGTN-Nurin** [TwistedGate/ImmersivePetroleum#92]
### Minecraft Version

1.16.5

### Immersive Engineering Version

5.1.0-148

### Immersive Petroleum Version

3.4.0-13

### Current Behaviour

Built pumpjack multiblock, formed it with the engineer's hammer and hooked up the IE fluid pipe to it to link it back to the refinery area I built. Wired it to power grid and it remained inert even after reforming it and replacing the fluid pipe. Placing a storage medium caused it to function as it should, and promptly filled it.

### Expected Behaviour

Pumpjack exporting through the fluid pipe to refinery area for refinement in the Distillation Tower.

### Reproduction Steps

1. Built pumpjack
2. Built distillation tower
3. Connected required power sources and fluid transfer blocks
4. Activate

### Debug Crash Log

https://gist.github.com/MGTN-Nurin/a22e00703204b3183de7a58b70f24f3d

### Information for the reader.

* Add a :thumbsup: to the bug report if you are also affected. This helps show the severity of this bug report and doesn't clutter the comments.
* Add a comment *if* you have any insights or background information that *isn't already part of the conversation*.

**Comment by TwistedGate** [comment]
Did you even correctly place the Pumpjack in a Chunk that has a Reservoir?

**Comment by MGTN-Nurin** [comment]
Yes, pumpjack was correctly placed in a chunk that was confirmed to have a crude oil reservoir

**Comment by TwistedGate** [comment]
So the head of the pumpjack is still within the chunk?
The pipes connect to an input? (Marked Blue)

(Screenshots would be nice too)

**Comment by MGTN-Nurin** [comment]
Confirmation that the chunk is an oil chunk [can also see that the pumpjack is within the same chunk by the minimap]
![2022-08-03_06 52 49](https://user-images.githubusercontent.com/99566440/182641155-cb86c3fc-0bfb-4522-94a8-3a2e8034b25b.png)
Showing positive connection into pipe
![2022-08-03_06 54 13](https://user-images.githubusercontent.com/99566440/182641105-a2f48886-665f-4187-a9b2-4cecaa04af1e.png)
Which feeds all the way to the end of the tunnel
![2022-08-03_06 56 04](https://user-images.githubusercontent.com/99566440/182641128-1d579561-5d1c-43e9-97fe-447f514c89f1.png)
And feeds into the distillation tower
![2022-08-03_06 56 13](https://user-images.githubusercontent.com/99566440/182641137-af948fd9-7a9f-4d2b-99ac-bcdd3bfe80d5.png)

**Comment by TwistedGate** [comment]
Last image, thats an output. The fluid input is below where the power goes in on the right.

On the left is output, and on the right is oil input.
![grafik](https://user-images.githubusercontent.com/31029668/182657190-4230011b-df01-4162-a310-b6538b19aa76.png)

**Comment by MGTN-Nurin** [comment]
...
__I am so sorry__
Thanks for the help, sorry for wasting your time. >~<
