### ISSUE TITLE
[Suggestion] Change Build Forge Version for 1.18.2 dev branch to 40.1.80

### ISSUE THREAD

**Issue by MCJEModder2026** [TwistedGate/ImmersivePetroleum#99]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

Doesent actually matter but will help some people with ocd
this is as of commit 5da9349b44b44b67f6480d4399ff2db6169eb208
- build with newer forge shasum `2d67e6097df0983f99219896572700c91085b196`
- build with forge 40.1.48 shasum `dc0681e1c6a59dfd31c18f403902833aaf786b7d`
my built jars: [TheKidThatBuildsJars.zip](https://github.com/TwistedGate/ImmersivePetroleum/files/9701950/TheKidThatBuildsJars.zip)

**Comment by TwistedGate** [comment]
What? No lol

I only ever update forge when i *absolutely have to* =P
